<?php 
/**
 * Hook menu
 * 
 */
function d3t_menu(){
	$items = array();
	
	$items['d3t'] = array(
			'page callback' => 'd3t_view_graph',
			'access callback' => true,
			'type' => MENU_CALLBACK, 
			'file' => 'd3t.inc',
	);
	$items['d3t/content'] = array(
			'page callback' => 'd3t_content',
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'file' => 'd3t.inc',
	);
	$items['d3t/graph/D/%'] = array(
			'page callback' => 'd3t_graph_discipline',
			'page arguments' => array(3),
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'file' => 'd3t.inc',
	);
	$items['d3t/graph/M/%'] = array(
			'page callback' => 'd3t_graph_mappe_tematiche',
			'page arguments' => array(3),
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'file' => 'd3t.inc',
	);
	$items['d3t/discipline.json'] = array(
			'page callback' => 'd3t_discipline_json',
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'file' => 'd3t.inc',
	);
	$items['d3t/aree_tematiche.json'] = array(
			'page callback' => 'd3t_aree_tematiche_json',
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'file' => 'd3t.inc',
	);
	$items['d3t/testdata.json'] = array(
			'page callback' => 'd3t_test_data_json',
			'access callback' => true,
			'type' => MENU_CALLBACK,
			'file' => 'd3t.inc',
	);
	return $items;
}
/**
 * Hook block_info
 * 
 */
function d3t_block_info(){
	return array(
			'graph' => array('info' => t('Grafico mappe tematiche')),
			'graph_content' => array('info' => t('Contenuti mappe tematiche'))
	);
}
/**
 * Hook view
 * 
 */
function d3t_block_view($delta){
	$block = array();
	switch($delta){
		case 'graph':
			$block['subject'] = '';
			$block['content'] = array(
				'#markup' => '<div class="selector">
					<span id="label-aree-tematiche">Aree tematiche:</span><ul id="aree-tematiche"></ul>
					<span id="labe-discipline">Discipline:</span><ul id="discipline"></ul></div><div class="graph"></div>',
  			'#attached' => array(
      		'css' => array(
      				drupal_get_path('module', 'd3t') . '/css/graph.css',
      		),
      		'js' => array(
        		drupal_get_path('module', 'd3t') . '/js/modernizr.js',
      			drupal_get_path('module', 'd3t') . '/js/d3.v3.js',
      			drupal_get_path('module', 'd3t') . '/js/graph.js'
    			),
  			),
  		);
		break;
		case 'graph_content':
			$block['subject'] = '';
			$block['content'] = array('#markup' => '<div id="graph-content-container"></div>');
		break;
	}
	return $block;
}

